SELECT ol.PRODUCT_ID, p.PRODUCT_DESCRIPTION
FROM ORDER_LINE ol
JOIN PRODUCT p ON ol.PRODUCT_ID = p.PRODUCT_ID
GROUP BY ol.PRODUCT_ID, p.PRODUCT_DESCRIPTION
ORDER BY SUM(ol.ORDERED_QUANTITY) DESC
LIMIT 1;
